<a href="https://colab.research.google.com/github/gaborh0808/1st-PyCrawlerMarathon/blob/master/LightBGM_20260817.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Jensen
import datetime
import warnings
import lightgbm as lgb
import numpy as np
import pandas as pd
import yfinance as yf

warnings.filterwarnings('ignore')

# 嘗試匯入 display（相容 Jupyter 與一般 .py 腳本）
try:
  from IPython.display import display
except ImportError:

  def display(x):
    print(x)


# 1. 配置股票池
stock_dict = {

   # --- 【新增：指定台股 ETF 族群】 ---
    "0050.TW": "元大台灣50",
    "0056.TW": "元大高股息",
    "00878.TW": "國泰永續高股息",
    "00770.TW": "國泰北美科技",
    "00981A.TW": "統一台股增長主動式",
    # --- 【新增：美股重點個股與 ETF】 ---
    "AAPL": "Apple 蘋果",
    "GOOG": "Google / Alphabet",
    "META": "Meta",
    "MSFT": "Microsoft 微軟",
    "NVDA": "NVIDIA 輝達",
    "TSM": "台積電 ADR",
    "TSLA": "Tesla 特斯拉",
    "ENTG": "Entegris 英特格",
    "SMR": "NuScale Power 小型核反應爐",
    "BE": "Bloom Energy 燃料電池",
    "JNJ": "Johnson & Johnson 嬌生",
    "SPCX": "SPACs ETF",
    # --- 【1. AI 伺服器與 ODM 概念股】 ---
    "2382.TW": "廣達",
    "3231.TW": "緯創",
    "6669.TW": "緯穎",
    "2317.TW": "鴻海",
    "2356.TW": "英業達",
    "2324.TW": "仁寶",
    "2376.TW": "技嘉",
    "3706.TW": "神達",
    "2377.TW": "微星",
    "2357.TW": "華碩",
    "4938.TW": "和碩",
    "3005.TW": "神基",
    "5274.TWO": "信驊",
    # --- 【2. 湧德與磁性元件 / 網通高速連接器概念股】 ---
    "3689.TWO": "湧德",
    "3357.TWO": "臺慶科",
    "6862.TW": "三集瑞-KY",
    "6821.TWO": "聯寶",
    "3207.TWO": "耀勝",
    "6197.TW": "佳必琪",
    "8103.TW": "瀚荃",
    "3526.TWO": "凡甲",
    "3605.TW": "宏致",
    # --- 【3. 網通 / 網路設備概念股】 ---
    "2345.TW": "智邦",
    "5388.TW": "中磊",
    "3558.TWO": "神準",
    "3704.TW": "合勤控",
    "4906.TW": "正文",
    # --- 【4. AI伺服器機殼 / 機構件與電子零組件概念股】 ---
    "8210.TW": "勤誠",
    "6117.TW": "迎廣",
    "6235.TW": "華孚",
    "2354.TW": "鴻準",
    "3376.TW": "新日興",
    "3548.TWO": "兆利",
    "5243.TW": "乙盛-KY",
    # --- 【5. 高速傳輸 / 介面IC / PCIe / USB4 概念股】 ---
    "4966.TWO": "譜瑞-KY",
    "5269.TW": "祥碩",
    "6104.TWO": "創惟",
    "6756.TW": "威鋒電子",
    "6715.TW": "嘉基",
    # --- 【6. AI 連接器 / 高速傳輸概念股】 ---
    "3533.TW": "嘉澤",
    "3217.TWO": "優群",
    "3023.TW": "信邦",
    "2392.TW": "正崴",
    # --- 【7. AI 核心 / 晶片設計 / ASIC 概念股】 ---
    "3035.TW": "智原",
    "6643.TWO": "M31",
    # --- 【8. AI電源供應器 / HVDC / 伺服器電源概念股】 ---
    "2308.TW": "台達電",
    "2301.TW": "光寶科",
    "6282.TW": "康舒",
    "6412.TW": "群電",
    "3665.TW": "貿聯-KY",
    # --- 【9. 液冷散熱 / 散熱模組概念股】 ---
    "3017.TW": "奇鋐",
    "3324.TWO": "雙鴻",
    "3653.TW": "健策",
    "2421.TW": "建準",
    "8996.TW": "高力",
    "3483.TWO": "力致",
    "6230.TW": "尼得科超眾",
    "3013.TW": "晟銘電",
    "6805.TW": "富世達",
    # --- 【10. BBU 備援電池模組相關概念股】 ---
    "6781.TW": "AES-KY",
    "3211.TWO": "順達",
    "6121.TWO": "新普",
    "3323.TWO": "加百裕",
    "3625.TWO": "西勝",
    "8038.TWO": "長園科",
    "4931.TWO": "新盛力",
    # --- 【11. 電力概念股 (重電、變壓器、電線電纜、儲能)】 ---
    "1519.TW": "華城",
    "1513.TW": "中興電",
    "1514.TW": "亞力",
    "1503.TW": "士電",
    "1609.TW": "大亞",
    "1605.TW": "華新",
    "1608.TW": "華榮",
    "6869.TW": "雲豹能源",
    # --- 【12. PCB / ABF載板 / CCL 相關概念股】 ---
    "3037.TW": "欣興",
    "8046.TW": "南電",
    "3189.TW": "景碩",
    "4958.TW": "臻鼎-KY",
    "2368.TW": "金像電",
    "3044.TW": "健鼎",
    "2313.TW": "華通",
    "8155.TWO": "博智",
    "2383.TW": "台光電",
    "6274.TWO": "台燿",
    "6213.TW": "聯茂",
    # --- 【13. 記憶體相關概念股】 ---
    "2344.TW": "華邦電",
    "2408.TW": "南亞科",
    "2337.TW": "旺宏",
    "3006.TW": "晶豪科",
    "3260.TWO": "威剛",
    "2451.TW": "創見",
    "4967.TW": "十銓",
    "8271.TW": "宇瞻",
    "5289.TWO": "宜鼎",
    "8299.TWO": "群聯",
    "5351.TWO": "鈺創",
    # --- 【14. 光通訊 / 矽光子 / CPO 概念股】 ---
    "4979.TWO": "華星光",
    "6442.TW": "光聖",
    "4908.TWO": "前鼎",
    "3163.TWO": "波若威",
    "3450.TW": "聯鈞",
    "6426.TW": "統新",
    "4977.TW": "眾達-KY",
    "6530.TWO": "創威",
    "3363.TWO": "上詮",
    "3234.TWO": "光環",
    "4903.TWO": "聯光通",
    "3081.TWO": "聯亞",
    "4991.TWO": "環宇-KY",
    "4971.TWO": "IET-KY",
    "6588.TWO": "東典光電",
    # --- 【15. 低軌衛星 / 太空通訊概念股】 ---
    "3491.TWO": "昇達科",
    "2314.TW": "台揚",
    "6285.TW": "啟碁",
    "3105.TWO": "穩懋",
    "2455.TW": "全新",
    "3138.TW": "耀登",
    "2419.TW": "仲琦",
    # --- 【16. 被動元件族群】 ---
    "2327.TW": "國巨",
    "2492.TW": "華新科",
    "2375.TW": "凱美",
    "2478.TW": "大毅",
    "3026.TW": "禾伸堂",
    "3090.TW": "日電貿",
    "6173.TWO": "信昌電",
    "6155.TW": "鈞寶",
    "6175.TWO": "立敦",
    "5328.TWO": "華容",
    "3236.TWO": "千如",
    # --- 【17. 機器人相關概念股】 ---
    "2049.TW": "上銀",
    "4576.TW": "大銀微系統",
    "4585.TW": "達明",
    "2359.TW": "所羅門",
    "6188.TWO": "廣明",
    "8374.TW": "羅昇",
    "5443.TWO": "均豪",
    "6640.TWO": "均華",
    "2464.TW": "盟立",
    "6215.TW": "和椿",
    "4562.TW": "穎漢",
    "1590.TW": "亞德客-KY",
    "1504.TW": "東元",
    # --- 【18. 半導體封裝與設備概念股】 ---
    "3711.TW": "日月光投控",
    "2449.TW": "京元電子",
    "6257.TW": "矽格",
    "3264.TWO": "欣銓",
    "6239.TW": "力成",
    "2329.TW": "華泰",
    "2441.TW": "超豐",
    "3131.TWO": "弘塑",
    "3583.TW": "辛耘",
    "6187.TWO": "萬潤",
    "2467.TW": "志聖",
    "8027.TWO": "鈦昇",
    "3481.TW": "群創",
    "2409.TW": "友達",
    # --- 【19. 半導體應用材料 / 耗材概念股】 ---
    "5434.TW": "崇越",
    "3010.TW": "華立",
    "1560.TW": "中砂",
    "3680.TWO": "家登",
    "5234.TW": "達興材料",
    "4749.TWO": "新應材",
    "8028.TW": "昇陽半導體",
    "6515.TW": "穎崴",
    "6683.TWO": "雍智科技",
    "6510.TWO": "精測",
    "6223.TWO": "旺矽",
    # --- 【20. 核心半導體 / IC設計 / 晶圓代工】 ---
    "2330.TW": "台積電",
    "2303.TW": "聯電",
    "2454.TW": "聯發科",
    "3034.TW": "聯詠",
    "3661.TW": "世芯-KY",
    "3443.TW": "創意",
    "4961.TW": "天鈺",
    "6415.TW": "矽力-KY",
    "6531.TW": "愛普*",
    # --- 【21. 家登概念股 / 半導體載具與設備夥伴】 ---
    "2404.TW": "漢唐",
    "1773.TW": "勝一",
    # --- 【22. 光學鏡頭與先進設備】 ---
    "3008.TW": "大立光",
    "4915.TW": "先進光",
    "5288.TW": "匯鑽科",
    "3644.TWO": "凌嘉科",
    "7769.TW": "鴻勁",
    "1303.TW": "南亞",
    # --- 【23. 工業電腦 (IPC) 相關概念股】 ---
    "2395.TW": "研華",
    "6166.TW": "凌華",
    "8050.TWO": "廣積",
    "3556.TWO": "禾瑞亞",
    "2414.TW": "精技",
    "6414.TW": "樺漢",
    "3022.TW": "威強電",
    "2397.TW": "友通",
    "5314.TWO": "世紀",
    "2393.TW": "億光",
    "2465.TW": "麗臺",
    "5536.TWO": "聖暉*",
    # --- 【24. 電動車 (EV) 與車用電子相關概念股】 ---
    "2201.TW": "裕隆",
    "2204.TW": "中華",
    "2206.TW": "三陽工業",
    "1536.TW": "和大",
    "2231.TW": "聯嘉",
    "3552.TWO": "同致",
    "6279.TWO": "胡連",
    # --- 【25. 其他與基礎建設】 ---
    "2353.TW": "宏碁",
    "8163.TW": "達方",
    "8043.TWO": "蜜望實",
    "2892.TW": "第一金",
    "5880.TW": "合庫金",
    "1210.TW": "大成",
    "1215.TW": "卜蜂",
    "1216.TW": "統一",
    "2912.TW": "統一超",
    "5903.TWO": "全家",
    "6770.TW": "力積電",
    "2342.TW": "茂矽",
    "3707.TWO": "漢磊",
    "3016.TW": "嘉晶",
    "6196.TW": "帆宣",
    "6139.TW": "亞翔",
    "6613.TWO": "朋億*",
    "4755.TW": "三福化",
    "4768.TWO": "晶呈科技",
    "3563.TW": "牧德",
    "1717.TW": "長興",
    "1815.TWO": "富喬",
    "1802.TW": "台玻",
    "5340.TWO": "建榮",
    "5475.TWO": "德宏",
    "3167.TW": "大量",
    "6438.TW": "迅得",
    "1595.TWO": "川寶",
    "6147.TWO": "頎邦",
    "8150.TW": "南茂",
    "6552.TW": "易華電",
    "3305.TW": "昇貿",
    "3631.TWO": "晟楠",
    "2059.TW": "川湖",
    "6584.TWO": "南俊國際",
    "8358.TWO": "金居",
    "8021.TW": "尖點",
    "6672.TW": "騰輝電子-KY",
}


def apply_labeling(df, upper=0.10, lower=-0.05, horizon=10):
  closes = df['Close'].values
  highs = df['High'].values
  lows = df['Low'].values
  labels = np.zeros(len(df))
  for i in range(len(df) - horizon):
    entry_p = closes[i]
    hit = 0
    for step in range(1, horizon + 1):
      if (lows[i + step] - entry_p) / entry_p <= lower:
        break
      if (highs[i + step] - entry_p) / entry_p >= upper:
        hit = 1
        break
    labels[i] = hit
  df['Target'] = labels
  return df


def compute_enhanced_features(df, market_df):
  d = df.copy()
  # 個股特徵
  ma5 = d['Close'].rolling(5).mean()
  ma10 = d['Close'].rolling(10).mean()
  ma20 = d['Close'].rolling(20).mean()
  d['MA_Tangle'] = (
      pd.concat([ma5, ma10, ma20], axis=1).max(axis=1)
      - pd.concat([ma5, ma10, ma20], axis=1).min(axis=1)
  ) / (ma20 + 1e-6)
  d['Vol_5MA'] = d['Volume'].rolling(5).mean()
  d['Vol_Ratio'] = d['Volume'] / (d['Vol_5MA'] + 1e-6)
  d['BIAS_5'] = (d['Close'] - ma5) / (ma5 + 1e-6)

  # 大盤增強特徵
  m_close = market_df['Close']
  d['Mkt_Alpha'] = d['Close'].pct_change(5) - m_close.pct_change(5)
  delta = m_close.diff()
  gain = delta.where(delta > 0, 0).rolling(14).mean()
  loss = (-delta.where(delta < 0, 0)).rolling(14).mean()
  rs = gain / (loss + 1e-6)
  d['Mkt_RSI'] = 100 - (100 / (1 + rs))
  d['Mkt_Vola'] = m_close.pct_change().rolling(20).std()

  cols = ['Vol_Ratio', 'BIAS_5', 'Mkt_Alpha', 'Mkt_RSI', 'Mkt_Vola']
  for c in cols:
    d[c] = d[c].shift(1)
  return d, cols


# 下載大盤數據
print('正在下載大盤 (^TWII) 數據...')
market_df = yf.download('^TWII', period='4y', progress=False)
market_df.columns = (
    market_df.columns.get_level_values(0)
    if isinstance(market_df.columns, pd.MultiIndex)
    else market_df.columns
)

all_results = []
models_cache = {}  # 儲存訓練好的模型與特徵欄位，供盤後預測直接調用
split_date = '2026-03-31'

print('\n開始訓練各個個股獨立模型 (回測階段)...')
for ticker, name in stock_dict.items():
  try:
    df = yf.download(ticker, period='4y', progress=False)
    if len(df) < 250:
      continue
    df.columns = (
        df.columns.get_level_values(0)
        if isinstance(df.columns, pd.MultiIndex)
        else df.columns
    )

    df = apply_labeling(df)
    df, f_cols = compute_enhanced_features(df, market_df)
    df = df.dropna(subset=f_cols + ['Target'])

    # 儲存完整資料供後續即時預測使用
    models_cache[ticker] = {'df_full': df, 'f_cols': f_cols}

    train = df[df.index <= split_date]
    test = df[(df.index > split_date) & (df.index <= '2026-06-30')]

    if len(train) < 100 or len(test) == 0:
      continue

    # 訓練回測模型
    model = lgb.LGBMClassifier(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=3,
        random_state=42,
        verbose=-1,
    )
    model.fit(train[f_cols], train['Target'])

    test = test.copy()
    test['Prob'] = model.predict_proba(test[f_cols])[:, 1]
    test['Ticker'] = ticker
    test['Name'] = name
    all_results.append(test[['Ticker', 'Name', 'Target', 'Prob']])
  except Exception as e:
    continue

if all_results:
  final_test = pd.concat(all_results).sort_values(by='Prob', ascending=False)
  threshold = 0.51
  signals = final_test[final_test['Prob'] >= threshold]
  print(
      f'\n=== LGBM_ST2: 每檔股票獨立建模 + 大盤特徵 (門檻 >='
      f' {int(threshold*100)}%) ==='
  )
  if not signals.empty:
    precision = (signals['Target'].sum() / len(signals)) * 100
    print(
        f"總訊號數: {len(signals)} | 成功數: {int(signals['Target'].sum())} |"
        f' 勝率: {precision:.2f}%'
    )
    display(signals.head(20))
  else:
    print('無符合門檻之訊號')

# --- 最新盤後預測 (直接使用快取模型訓練至最新，省去重複下載) ---
print('\n正在產生最新交易建議...')
prediction_results = []

for ticker, name in stock_dict.items():
  if ticker not in models_cache:
    continue
  try:
    # 抓取最新 1 個月資料來取得最新特徵值
    df_latest = yf.download(ticker, period='1mo', progress=False)
    if len(df_latest) < 20:
      continue
    df_latest.columns = (
        df_latest.columns.get_level_values(0)
        if isinstance(df_latest.columns, pd.MultiIndex)
        else df_latest.columns
    )

    df_feat, f_cols = compute_enhanced_features(df_latest, market_df)
    latest_X = df_feat[f_cols].tail(1)
    if latest_X.isnull().values.any():
      continue

    # 使用該股票快取的完整歷史資料重新訓練至最新狀態
    cached_data = models_cache[ticker]
    df_train = cached_data['df_full'].dropna(
        subset=cached_data['f_cols'] + ['Target']
    )

    final_model = lgb.LGBMClassifier(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=3,
        random_state=42,
        verbose=-1,
    )
    final_model.fit(df_train[cached_data['f_cols']], df_train['Target'])

    prob = final_model.predict_proba(latest_X)[0][1]

    prediction_results.append({
        '股票名稱': name,
        '股票代號': ticker.split('.')[0],
        '預測漲幅機率': f'{round(float(prob) * 100, 2)}%',
        'raw_prob': float(prob),
    })
  except Exception as e:
    continue

suggestion_df = pd.DataFrame(prediction_results).sort_values(
    by='raw_prob', ascending=False
)

print(f'\n=== LGBM_ST2: {datetime.date.today()} 盤後預測建議 (明日交易參考) ===')
print(f'篩選準則：預測未來10日漲幅達10%之機率 >= {int(threshold*100)}%')

triggered = suggestion_df[suggestion_df['raw_prob'] >= 0.51]
if not triggered.empty:
  display(triggered[['股票名稱', '股票代號', '預測漲幅機率']])
else:
  print('今日無符合門檻之強勢標的。')

正在下載大盤 (^TWII) 數據...

開始訓練各個個股獨立模型 (回測階段)...

=== LGBM_ST2: 每檔股票獨立建模 + 大盤特徵 (門檻 >= 51%) ===
總訊號數: 2347 | 成功數: 1072 | 勝率: 45.68%

Price         Ticker Name  Target      Prob
Date
2026-06-05   2337.TW   旺宏     0.0  0.990794
2026-06-05   2303.TW   聯電     0.0  0.985666
2026-06-04   2303.TW   聯電     0.0  0.985666
2026-04-30  3131.TWO   弘塑     0.0  0.981530
2026-04-29  6187.TWO   萬潤     1.0  0.972757
2026-05-12  6187.TWO   萬潤     0.0  0.972148
2026-04-28  6187.TWO   萬潤     1.0  0.971618
2026-06-12  6147.TWO   頎邦     1.0  0.969056
2026-04-28   2342.TW   茂矽     1.0  0.947322
2026-06-10  6147.TWO   頎邦     0.0  0.946895
2026-04-30  6187.TWO   萬潤     1.0  0.944264
2026-04-28  8358.TWO   金居     1.0  0.942938
2026-05-12   3017.TW   奇鋐     1.0  0.939373
2026-05-11  6187.TWO   萬潤     1.0  0.938126
2026-04-30   8046.TW   南電     0.0  0.933252
2026-05-13   3017.TW   奇鋐     0.0  0.931119
2026-04-27   6155.TW   鈞寶     1.0  0.930194
2026-05-14   8210.TW   勤誠     0.0  0.929706
2026-06-03  3081.TWO   聯亞     0.0  0.928342
2026-04-27  6187.TWO   萬潤     1.0  0.926456

正在產生最新交易建議...

=== LGBM_ST2: 2026-08-17 盤後預測建議 (明日交易參考) ===
篩選準則：預測未來10日漲幅達10%之機率 >= 51%

    股票名稱  股票代號  預測漲幅機率
120   上詮  3363  52.23%

In [4]:
#無均線糾結升級為lightgbm優化模式
import warnings
import lightgbm as lgb
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import yfinance as yf

# 忽略不必要的警告訊息
warnings.filterwarnings("ignore")

# 股票代號與名稱對應字典
stock_dict = {
    # --- 【新增：指定台股 ETF 族群】 ---
    "0050.TW": "元大台灣50",
    "0056.TW": "元大高股息",
    "00878.TW": "國泰永續高股息",
    "00770.TW": "國泰北美科技",
    "00981A.TW": "統一台股增長主動式",
    # --- 【新增：美股重點個股與 ETF】 ---
    "AAPL": "Apple 蘋果",
    "GOOG": "Google / Alphabet",
    "META": "Meta",
    "MSFT": "Microsoft 微軟",
    "NVDA": "NVIDIA 輝達",
    "TSM": "台積電 ADR",
    "TSLA": "Tesla 特斯拉",
    "ENTG": "Entegris 英特格",
    "SMR": "NuScale Power 小型核反應爐",
    "BE": "Bloom Energy 燃料電池",
    "JNJ": "Johnson & Johnson 嬌生",
    "SPCX": "SPACs ETF",
    # --- 【1. AI 伺服器與 ODM 概念股】 ---
    "2382.TW": "廣達",
    "3231.TW": "緯創",
    "6669.TW": "緯穎",
    "2317.TW": "鴻海",
    "2356.TW": "英業達",
    "2324.TW": "仁寶",
    "2376.TW": "技嘉",
    "3706.TW": "神達",
    "2377.TW": "微星",
    "2357.TW": "華碩",
    "4938.TW": "和碩",
    "3005.TW": "神基",
    "5274.TWO": "信驊",
    # --- 【2. 湧德與磁性元件 / 網通高速連接器概念股】 ---
    "3689.TWO": "湧德",
    "3357.TWO": "臺慶科",
    "6862.TW": "三集瑞-KY",
    "6821.TWO": "聯寶",
    "3207.TWO": "耀勝",
    "6197.TW": "佳必琪",
    "8103.TW": "瀚荃",
    "3526.TWO": "凡甲",
    "3605.TW": "宏致",
    # --- 【3. 網通 / 網路設備概念股】 ---
    "2345.TW": "智邦",
    "5388.TW": "中磊",
    "3558.TWO": "神準",
    "3704.TW": "合勤控",
    "4906.TW": "正文",
    # --- 【4. AI伺服器機殼 / 機構件與電子零組件概念股】 ---
    "8210.TW": "勤誠",
    "6117.TW": "迎廣",
    "6235.TW": "華孚",
    "2354.TW": "鴻準",
    "3376.TW": "新日興",
    "3548.TWO": "兆利",
    "5243.TW": "乙盛-KY",
    # --- 【5. 高速傳輸 / 介面IC / PCIe / USB4 概念股】 ---
    "4966.TWO": "譜瑞-KY",
    "5269.TW": "祥碩",
    "6104.TWO": "創惟",
    "6756.TW": "威鋒電子",
    "6715.TW": "嘉基",
    # --- 【6. AI 連接器 / 高速傳輸概念股】 ---
    "3533.TW": "嘉澤",
    "3217.TWO": "優群",
    "3023.TW": "信邦",
    "2392.TW": "正崴",
    # --- 【7. AI 核心 / 晶片設計 / ASIC 概念股】 ---
    "3035.TW": "智原",
    "6643.TWO": "M31",
    # --- 【8. AI電源供應器 / HVDC / 伺服器電源概念股】 ---
    "2308.TW": "台達電",
    "2301.TW": "光寶科",
    "6282.TW": "康舒",
    "6412.TW": "群電",
    "3665.TW": "貿聯-KY",
    # --- 【9. 液冷散熱 / 散熱模組概念股】 ---
    "3017.TW": "奇鋐",
    "3324.TWO": "雙鴻",
    "3653.TW": "健策",
    "2421.TW": "建準",
    "8996.TW": "高力",
    "3483.TWO": "力致",
    "6230.TW": "尼得科超眾",
    "3013.TW": "晟銘電",
    "6805.TW": "富世達",
    # --- 【10. BBU 備援電池模組相關概念股】 ---
    "6781.TW": "AES-KY",
    "3211.TWO": "順達",
    "6121.TWO": "新普",
    "3323.TWO": "加百裕",
    "3625.TWO": "西勝",
    "8038.TWO": "長園科",
    "4931.TWO": "新盛力",
    # --- 【11. 電力概念股 (重電、變壓器、電線電纜、儲能)】 ---
    "1519.TW": "華城",
    "1513.TW": "中興電",
    "1514.TW": "亞力",
    "1503.TW": "士電",
    "1609.TW": "大亞",
    "1605.TW": "華新",
    "1608.TW": "華榮",
    "6869.TW": "雲豹能源",
    # --- 【12. PCB / ABF載板 / CCL 相關概念股】 ---
    "3037.TW": "欣興",
    "8046.TW": "南電",
    "3189.TW": "景碩",
    "4958.TW": "臻鼎-KY",
    "2368.TW": "金像電",
    "3044.TW": "健鼎",
    "2313.TW": "華通",
    "8155.TWO": "博智",
    "2383.TW": "台光電",
    "6274.TWO": "台燿",
    "6213.TW": "聯茂",
    # --- 【13. 記憶體相關概念股】 ---
    "2344.TW": "華邦電",
    "2408.TW": "南亞科",
    "2337.TW": "旺宏",
    "3006.TW": "晶豪科",
    "3260.TWO": "威剛",
    "2451.TW": "創見",
    "4967.TW": "十銓",
    "8271.TW": "宇瞻",
    "5289.TWO": "宜鼎",
    "8299.TWO": "群聯",
    "5351.TWO": "鈺創",
    # --- 【14. 光通訊 / 矽光子 / CPO 概念股】 ---
    "4979.TWO": "華星光",
    "6442.TW": "光聖",
    "4908.TWO": "前鼎",
    "3163.TWO": "波若威",
    "3450.TW": "聯鈞",
    "6426.TW": "統新",
    "4977.TW": "眾達-KY",
    "6530.TWO": "創威",
    "3363.TWO": "上詮",
    "3234.TWO": "光環",
    "4903.TWO": "聯光通",
    "3081.TWO": "聯亞",
    "4991.TWO": "環宇-KY",
    "4971.TWO": "IET-KY",
    "6588.TWO": "東典光電",
    # --- 【15. 低軌衛星 / 太空通訊概念股】 ---
    "3491.TWO": "昇達科",
    "2314.TW": "台揚",
    "6285.TW": "啟碁",
    "3105.TWO": "穩懋",
    "2455.TW": "全新",
    "3138.TW": "耀登",
    "2419.TW": "仲琦",
    # --- 【16. 被動元件族群】 ---
    "2327.TW": "國巨",
    "2492.TW": "華新科",
    "2375.TW": "凱美",
    "2478.TW": "大毅",
    "3026.TW": "禾伸堂",
    "3090.TW": "日電貿",
    "6173.TWO": "信昌電",
    "6155.TW": "鈞寶",
    "6175.TWO": "立敦",
    "5328.TWO": "華容",
    "3236.TWO": "千如",
    # --- 【17. 機器人相關概念股】 ---
    "2049.TW": "上銀",
    "4576.TW": "大銀微系統",
    "4585.TW": "達明",
    "2359.TW": "所羅門",
    "6188.TWO": "廣明",
    "8374.TW": "羅昇",
    "5443.TWO": "均豪",
    "6640.TWO": "均華",
    "2464.TW": "盟立",
    "6215.TW": "和椿",
    "4562.TW": "穎漢",
    "1590.TW": "亞德客-KY",
    "1504.TW": "東元",
    # --- 【18. 半導體封裝與設備概念股】 ---
    "3711.TW": "日月光投控",
    "2449.TW": "京元電子",
    "6257.TW": "矽格",
    "3264.TWO": "欣銓",
    "6239.TW": "力成",
    "2329.TW": "華泰",
    "2441.TW": "超豐",
    "3131.TWO": "弘塑",
    "3583.TW": "辛耘",
    "6187.TWO": "萬潤",
    "2467.TW": "志聖",
    "8027.TWO": "鈦昇",
    "3481.TW": "群創",
    "2409.TW": "友達",
    # --- 【19. 半導體應用材料 / 耗材概念股】 ---
    "5434.TW": "崇越",
    "3010.TW": "華立",
    "1560.TW": "中砂",
    "3680.TWO": "家登",
    "5234.TW": "達興材料",
    "4749.TWO": "新應材",
    "8028.TW": "昇陽半導體",
    "6515.TW": "穎崴",
    "6683.TWO": "雍智科技",
    "6510.TWO": "精測",
    "6223.TWO": "旺矽",
    # --- 【20. 核心半導體 / IC設計 / 晶圓代工】 ---
    "2330.TW": "台積電",
    "2303.TW": "聯電",
    "2454.TW": "聯發科",
    "3034.TW": "聯詠",
    "3661.TW": "世芯-KY",
    "3443.TW": "創意",
    "4961.TW": "天鈺",
    "6415.TW": "矽力-KY",
    "6531.TW": "愛普*",
    # --- 【21. 家登概念股 / 半導體載具與設備夥伴】 ---
    "2404.TW": "漢唐",
    "1773.TW": "勝一",
    # --- 【22. 光學鏡頭與先進設備】 ---
    "3008.TW": "大立光",
    "4915.TW": "先進光",
    "5288.TW": "匯鑽科",
    "3644.TWO": "凌嘉科",
    "7769.TW": "鴻勁",
    "1303.TW": "南亞",
    # --- 【23. 工業電腦 (IPC) 相關概念股】 ---
    "2395.TW": "研華",
    "6166.TW": "凌華",
    "8050.TWO": "廣積",
    "3556.TWO": "禾瑞亞",
    "2414.TW": "精技",
    "6414.TW": "樺漢",
    "3022.TW": "威強電",
    "2397.TW": "友通",
    "5314.TWO": "世紀",
    "2393.TW": "億光",
    "2465.TW": "麗臺",
    "5536.TWO": "聖暉*",
    # --- 【24. 電動車 (EV) 與車用電子相關概念股】 ---
    "2201.TW": "裕隆",
    "2204.TW": "中華",
    "2206.TW": "三陽工業",
    "1536.TW": "和大",
    "2231.TW": "聯嘉",
    "3552.TWO": "同致",
    "6279.TWO": "胡連",
    # --- 【25. 其他與基礎建設】 ---
    "2353.TW": "宏碁",
    "8163.TW": "達方",
    "8043.TWO": "蜜望實",
    "2892.TW": "第一金",
    "5880.TW": "合庫金",
    "1210.TW": "大成",
    "1215.TW": "卜蜂",
    "1216.TW": "統一",
    "2912.TW": "統一超",
    "5903.TWO": "全家",
    "6770.TW": "力積電",
    "2342.TW": "茂矽",
    "3707.TWO": "漢磊",
    "3016.TW": "嘉晶",
    "6196.TW": "帆宣",
    "6139.TW": "亞翔",
    "6613.TWO": "朋億*",
    "4755.TW": "三福化",
    "4768.TWO": "晶呈科技",
    "3563.TW": "牧德",
    "1717.TW": "長興",
    "1815.TWO": "富喬",
    "1802.TW": "台玻",
    "5340.TWO": "建榮",
    "5475.TWO": "德宏",
    "3167.TW": "大量",
    "6438.TW": "迅得",
    "1595.TWO": "川寶",
    "6147.TWO": "頎邦",
    "8150.TW": "南茂",
    "6552.TW": "易華電",
    "3305.TW": "昇貿",
    "3631.TWO": "晟楠",
    "2059.TW": "川湖",
    "6584.TWO": "南俊國際",
    "8358.TWO": "金居",
    "8021.TW": "尖點",
    "6672.TW": "騰輝電子-KY",
}


def compute_features(df, market_df):
  """執行 4 大類特徵工程與防洩漏處理 (LightGBM 優化版)"""
  d = df.copy()

  # --- A. 價格型態與波動度特徵 ---
  d["Close_Slope"] = (
      d["Close"].rolling(5).apply(lambda x: np.polyfit(range(5), x, 1)[0], raw=True)
  )

  body = np.abs(d["Close"] - d["Open"])
  body_safe = np.where(body == 0, 1e-6, body)
  d["Upper_Shadow_Ratio"] = (
      d["High"] - np.maximum(d["Close"], d["Open"])
  ) / body_safe
  d["Lower_Shadow_Ratio"] = (
      np.minimum(d["Close"], d["Open"]) - d["Low"]
  ) / body_safe

  d["Gap"] = (d["Open"] - d["Close"].shift(1)) / d["Close"].shift(1)

  high_low = d["High"] - d["Low"]
  high_close = np.abs(d["High"] - d["Close"].shift(1))
  low_close = np.abs(d["Low"] - d["Close"].shift(1))
  tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
  atr14 = tr.rolling(14).mean()
  d["NATR"] = atr14 / d["Close"]

  ma20 = d["Close"].rolling(20).mean()
  std20 = d["Close"].rolling(20).std()
  upper_band = ma20 + (2 * std20)
  lower_band = ma20 - (2 * std20)
  d["BB_Bandwidth"] = (upper_band - lower_band) / ma20

  ma5 = d["Close"].rolling(5).mean()
  d["BIAS_5"] = (d["Close"] - ma5) / ma5

  # --- B. 量能與資金成本特徵 ---
  vol_mean5 = d["Volume"].rolling(5).mean()
  d["Volume_Explosion"] = d["Volume"] / (vol_mean5 + 1e-6)

  typical_price = (d["High"] + d["Low"] + d["Close"]) / 3
  vwap = (typical_price * d["Volume"]).rolling(5).sum() / (
      d["Volume"].rolling(5).sum() + 1e-6
  )
  d["VWAP_BIAS"] = (d["Close"] - vwap) / vwap

  obv = (np.sign(d["Close"].diff()) * d["Volume"]).fillna(0).cumsum()
  d["OBV_Slope"] = (
      obv.rolling(5).apply(lambda x: np.polyfit(range(5), x, 1)[0], raw=True)
  )
  d["Turnover_Rate"] = d["Volume"] / (d["Volume"].rolling(60).mean() + 1e-6)

  # --- C. 深層籌碼與信用交易特徵 ---
  d["Foreign_Buy_Ratio"] = 0.0
  d["Trust_Buy_Ratio"] = 0.0
  d["Inst_Sync"] = 0
  d["Margin_Change_5d"] = 0.0
  d["Short_Margin_Ratio"] = 0.0

  # --- D. 市場相對強度特徵 ---
  stock_ret5 = d["Close"].pct_change(5)
  market_ret5 = market_df["Close"].pct_change(5)
  d["Alpha_5d"] = stock_ret5 - market_ret5

  feature_cols = [
      "Close_Slope",
      "Upper_Shadow_Ratio",
      "Lower_Shadow_Ratio",
      "Gap",
      "NATR",
      "BB_Bandwidth",
      "BIAS_5",
      "Volume_Explosion",
      "VWAP_BIAS",
      "OBV_Slope",
      "Turnover_Rate",
      "Foreign_Buy_Ratio",
      "Trust_Buy_Ratio",
      "Inst_Sync",
      "Margin_Change_5d",
      "Short_Margin_Ratio",
      "Alpha_5d",
  ]

  # 特徵位移防洩漏
  for col in feature_cols:
    d[col] = d[col].shift(1)

  return d, feature_cols


print("步驟零：正在下載大盤基準資料 (^TWII)...")
market_df = yf.download("^TWII", period="3y", progress=False)
if isinstance(market_df.columns, pd.MultiIndex):
  market_df.columns = market_df.columns.get_level_values(0)

print(
    "步驟一：開始進行個股批次下載與運算，並產出最近 5 個交易日的逐日獨立模型預測..."
)
predictions = []

# 批次下載所有股票資料以大幅提升速度
all_tickers = list(stock_dict.keys())
batch_data = yf.download(all_tickers, period="2y", progress=False, group_by="ticker")

for ticker, name in stock_dict.items():
  try:
    if len(all_tickers) > 1:
      df = batch_data[ticker].dropna(how="all")
    else:
      df = batch_data.dropna(how="all")

    if df.empty or len(df) < 250:
      continue
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)

    # 標籤定義：未來 10 個交易日內最高價曾漲幅達 10%
    horizon = 10
    threshold = 0.10
    future_max = (
        df["Close"]
        .shift(-1)
        .iloc[::-1]
        .rolling(window=horizon, min_periods=1)
        .max()
        .iloc[::-1]
    )
    future_return = (future_max - df["Close"]) / df["Close"]
    df["Target"] = (future_return >= threshold).astype(int)

    # 執行特徵工程與防洩漏處理
    df_feat, feature_cols = compute_features(df, market_df)

    df_clean = df_feat.dropna(subset=feature_cols + ["Target"])
    if len(df_clean) < 60:
      continue

    # 迴圈計算最後 5 個交易日的逐日預測
    for i in range(-5, 0):
      X_train = df_clean[feature_cols].iloc[:i]
      y_train = df_clean["Target"].iloc[:i]

      if len(y_train) < 50 or len(y_train.unique()) < 2:
        continue

      # 極端值處理 (Winsorization 1% 至 99%)
      lower_bound = X_train.quantile(0.01)
      upper_bound = X_train.quantile(0.99)
      X_train_clipped = X_train.clip(lower_bound, upper_bound, axis=1)

      train_base = y_train.mean()

      # 切分出驗證集供 LightGBM 早停機制使用
      if len(X_train_clipped) > 30:
        X_tr, X_val, y_tr, y_val = train_test_split(
            X_train_clipped, y_train, test_size=0.2, shuffle=False
        )
      else:
        X_tr, X_val, y_tr, y_val = (
            X_train_clipped,
            X_train_clipped,
            y_train,
            y_train,
        )

      # 建立 LightGBM 模型並加入早停機制
      model = lgb.LGBMClassifier(
          n_estimators=300,
          learning_rate=0.03,
          max_depth=4,
          random_state=42,
          verbose=-1,
      )

      model.fit(
          X_tr,
          y_tr,
          eval_set=[(X_val, y_val)],
          callbacks=[lgb.early_stopping(stopping_rounds=30, verbose=False)],
      )

      # 取得目標當天的特徵
      target_features = df_clean[feature_cols].iloc[[i]].copy()
      target_features = target_features.clip(lower_bound, upper_bound, axis=1)

      if target_features.dropna().empty:
        continue

      prob = model.predict_proba(target_features)[0][1]
      lift_val = float(prob) / float(train_base) if train_base > 0 else 0.0
      pred_date = df_clean.index[i].strftime("%Y-%m-%d")

      predictions.append({
          "預測日期": pred_date,
          "股票名稱": name,
          "股票代號": ticker.split(".")[0],
          "Base y": f"{round(float(train_base) * 100, 2)}%",
          "raw_prob": float(prob),
          "y成立機率值": f"{round(float(prob) * 100, 2)}%",
          "10% Lift 值": f"{round(lift_val, 2)}x",
      })
  except Exception:
    pass

final_output_df = pd.DataFrame(predictions)
if not final_output_df.empty:
  final_output_df = final_output_df.sort_values(
      by=["預測日期", "raw_prob"], ascending=[False, False]
  )

  print("\n" + "=" * 75)
  print(" 最近 5 個交易日個股逐日預測結果清單 (LightGBM + 早停機制優化版) ")
  print("=" * 75)
  print(
      final_output_df[[
          "預測日期",
          "股票名稱",
          "股票代號",
          "Base y",
          "y成立機率值",
          "10% Lift 值",
      ]].to_markdown(index=False)
  )
else:
  print("目前無法產生預測結果。")

步驟零：正在下載大盤基準資料 (^TWII)...
步驟一：開始進行個股批次下載與運算，並產出最近 5 個交易日的逐日獨立模型預測...

===========================================================================
 最近 5 個交易日個股逐日預測結果清單 (LightGBM + 早停機制優化版)
===========================================================================
| 預測日期   | 股票名稱                   | 股票代號   | Base y   | y成立機率值   | 10% Lift 值   |
|:-----------|:---------------------------|:-----------|:---------|:--------------|:--------------|
| 2026-08-17 | 旺矽                       | 6223       | 48.93%   | 64.08%        | 1.31x         |
| 2026-08-17 | 萬潤                       | 6187       | 34.61%   | 59.41%        | 1.72x         |
| 2026-08-17 | 鈺創                       | 5351       | 36.52%   | 57.52%        | 1.58x         |
| 2026-08-17 | AES-KY                     | 6781       | 33.17%   | 57.08%        | 1.72x         |
| 2026-08-17 | 欣興                       | 3037       | 42.72%   | 56.68%        | 1.33x         |
| 2026-08-17 | 志聖                       | 2467       | 38.9%    | 56.34%        | 1.45x         |
| 2026-08-17 | 德宏                       | 5475       | 51.07%   | 55.41%        | 1.08x         |
| 2026-08-17 | 南電                       | 8046       | 45.11%   | 54.78%        | 1.21x         |
| 2026-08-17 | 南亞科                     | 2408       | 56.56%   | 54.11%        | 0.96x         |
| 2026-08-17 | 光聖                       | 6442       | 48.69%   | 53.19%        | 1.09x         |
| 2026-08-17 | 聯亞                       | 3081       | 51.07%   | 53.13%        | 1.04x         |
| 2026-08-17 | 南俊國際                   | 6584       | 42.0%    | 52.59%        | 1.25x         |
| 2026-08-17 | 蜜望實                     | 8043       | 41.05%   | 52.56%        | 1.28x         |
| 2026-08-17 | 頎邦                       | 6147       | 18.85%   | 52.08%        | 2.76x         |
| 2026-08-17 | 台光電                     | 2383       | 49.4%    | 51.63%        | 1.05x         |
| 2026-08-17 | 波若威                     | 3163       | 43.44%   | 50.85%        | 1.17x         |
| 2026-08-17 | 華星光                     | 4979       | 46.3%    | 50.7%         | 1.09x         |
| 2026-08-17 | 穎崴                       | 6515       | 47.49%   | 50.65%        | 1.07x         |
| 2026-08-17 | 環宇-KY                    | 4991       | 48.21%   | 50.59%        | 1.05x         |
| 2026-08-17 | 大量                       | 3167       | 49.88%   | 50.02%        | 1.0x          |
| 2026-08-17 | IET-KY                     | 4971       | 45.58%   | 48.67%        | 1.07x         |
| 2026-08-17 | 尖點                       | 8021       | 49.16%   | 48.3%         | 0.98x         |
| 2026-08-17 | 金居                       | 8358       | 43.91%   | 47.94%        | 1.09x         |
| 2026-08-17 | 友達                       | 2409       | 26.73%   | 47.81%        | 1.79x         |
| 2026-08-17 | 金像電                     | 2368       | 43.68%   | 47.76%        | 1.09x         |
| 2026-08-17 | 富喬                       | 1815       | 42.48%   | 47.21%        | 1.11x         |
| 2026-08-17 | 創意                       | 3443       | 41.53%   | 47.08%        | 1.13x         |
| 2026-08-17 | 昇達科                     | 3491       | 45.11%   | 46.75%        | 1.04x         |
| 2026-08-17 | 臻鼎-KY                    | 4958       | 31.98%   | 45.12%        | 1.41x         |
| 2026-08-17 | 鴻勁                       | 7769       | 41.35%   | 45.02%        | 1.09x         |
| 2026-08-17 | 上詮                       | 3363       | 43.2%    | 44.98%        | 1.04x         |
| 2026-08-17 | 台燿                       | 6274       | 44.15%   | 44.38%        | 1.01x         |
| 2026-08-17 | 精測                       | 6510       | 38.66%   | 43.64%        | 1.13x         |
| 2026-08-17 | 旺宏                       | 2337       | 38.9%    | 43.34%        | 1.11x         |
| 2026-08-17 | 十銓                       | 4967       | 28.88%   | 43.11%        | 1.49x         |
| 2026-08-17 | 新盛力                     | 4931       | 46.06%   | 42.84%        | 0.93x         |
| 2026-08-17 | 群創                       | 3481       | 29.59%   | 42.54%        | 1.44x         |
| 2026-08-17 | 愛普*                      | 6531       | 36.52%   | 42.46%        | 1.16x         |
| 2026-08-17 | 大銀微系統                 | 4576       | 31.26%   | 42.31%        | 1.35x         |
| 2026-08-17 | 順達                       | 3211       | 42.0%    | 42.16%        | 1.0x          |
| 2026-08-17 | 奇鋐                       | 3017       | 43.91%   | 42.13%        | 0.96x         |
| 2026-08-17 | 高力                       | 8996       | 43.68%   | 41.92%        | 0.96x         |
| 2026-08-17 | 雍智科技                   | 6683       | 39.14%   | 41.58%        | 1.06x         |
| 2026-08-17 | 健策                       | 3653       | 39.14%   | 40.88%        | 1.04x         |
| 2026-08-17 | 博智                       | 8155       | 35.8%    | 40.84%        | 1.14x         |
| 2026-08-17 | 貿聯-KY                    | 3665       | 42.0%    | 40.66%        | 0.97x         |
| 2026-08-17 | 創威                       | 6530       | 27.45%   | 40.4%         | 1.47x         |
| 2026-08-17 | 信驊                       | 5274       | 41.05%   | 40.22%        | 0.98x         |
| 2026-08-17 | 光環                       | 3234       | 40.33%   | 39.7%         | 0.98x         |
| 2026-08-17 | 建榮                       | 5340       | 40.81%   | 38.88%        | 0.95x         |
| 2026-08-17 | 穩懋                       | 3105       | 35.56%   | 38.63%        | 1.09x         |
| 2026-08-17 | 晶呈科技                   | 4768       | 33.17%   | 38.3%         | 1.15x         |
| 2026-08-17 | 亞翔                       | 6139       | 36.75%   | 38.24%        | 1.04x         |
| 2026-08-17 | 大毅                       | 2478       | 28.16%   | 38.21%        | 1.36x         |
| 2026-08-17 | 群聯                       | 8299       | 40.81%   | 38.12%        | 0.93x         |
| 2026-08-17 | 均華                       | 6640       | 35.32%   | 38.1%         | 1.08x         |
| 2026-08-17 | 全新                       | 2455       | 33.41%   | 38.02%        | 1.14x         |
| 2026-08-17 | 富世達                     | 6805       | 39.14%   | 38.01%        | 0.97x         |
| 2026-08-17 | 聯茂                       | 6213       | 38.42%   | 37.77%        | 0.98x         |
| 2026-08-17 | 智邦                       | 2345       | 36.28%   | 37.06%        | 1.02x         |
| 2026-08-17 | 凱美                       | 2375       | 31.26%   | 36.77%        | 1.18x         |
| 2026-08-17 | 聯光通                     | 4903       | 33.41%   | 36.41%        | 1.09x         |
| 2026-08-17 | 聯鈞                       | 3450       | 37.47%   | 35.97%        | 0.96x         |
| 2026-08-17 | 矽格                       | 6257       | 25.78%   | 35.97%        | 1.4x          |
| 2026-08-17 | 鈦昇                       | 8027       | 29.59%   | 35.75%        | 1.21x         |
| 2026-08-17 | 宜鼎                       | 5289       | 37.23%   | 35.45%        | 0.95x         |
| 2026-08-17 | 晶豪科                     | 3006       | 35.8%    | 35.31%        | 0.99x         |
| 2026-08-17 | 世芯-KY                    | 3661       | 36.52%   | 35.13%        | 0.96x         |
| 2026-08-17 | 眾達-KY                    | 4977       | 34.61%   | 34.98%        | 1.01x         |
| 2026-08-17 | 台玻                       | 1802       | 36.75%   | 34.93%        | 0.95x         |
| 2026-08-17 | 聖暉*                      | 5536       | 39.38%   | 34.75%        | 0.88x         |
| 2026-08-17 | 台達電                     | 2308       | 34.13%   | 34.65%        | 1.02x         |
| 2026-08-17 | 日月光投控                 | 3711       | 30.55%   | 34.48%        | 1.13x         |
| 2026-08-17 | 威剛                       | 3260       | 33.41%   | 34.42%        | 1.03x         |
| 2026-08-17 | 達興材料                   | 5234       | 29.59%   | 34.09%        | 1.15x         |
| 2026-08-17 | 弘塑                       | 3131       | 36.04%   | 33.88%        | 0.94x         |
| 2026-08-17 | 昇貿                       | 3305       | 31.74%   | 33.57%        | 1.06x         |
| 2026-08-17 | 加百裕                     | 3323       | 30.55%   | 33.34%        | 1.09x         |
| 2026-08-17 | 和椿                       | 6215       | 34.37%   | 33.31%        | 0.97x         |
| 2026-08-17 | 華通                       | 2313       | 32.94%   | 33.25%        | 1.01x         |
| 2026-08-17 | 三集瑞-KY                  | 6862       | 33.51%   | 33.04%        | 0.99x         |
| 2026-08-17 | 鈞寶                       | 6155       | 30.31%   | 32.94%        | 1.09x         |
| 2026-08-17 | 華城                       | 1519       | 30.31%   | 32.89%        | 1.09x         |
| 2026-08-17 | 辛耘                       | 3583       | 25.54%   | 32.83%        | 1.29x         |
| 2026-08-17 | 力積電                     | 6770       | 40.81%   | 32.55%        | 0.8x          |
| 2026-08-17 | 華泰                       | 2329       | 28.88%   | 32.13%        | 1.11x         |
| 2026-08-17 | 川湖                       | 2059       | 43.91%   | 32.06%        | 0.73x         |
| 2026-08-17 | 景碩                       | 3189       | 46.3%    | 32.0%         | 0.69x         |
| 2026-08-17 | 漢磊                       | 3707       | 37.71%   | 31.93%        | 0.85x         |
| 2026-08-17 | 昇陽半導體                 | 8028       | 33.41%   | 31.66%        | 0.95x         |
| 2026-08-17 | 雙鴻                       | 3324       | 31.26%   | 31.45%        | 1.01x         |
| 2026-08-17 | 東典光電                   | 6588       | 28.64%   | 31.25%        | 1.09x         |
| 2026-08-17 | 西勝                       | 3625       | 33.65%   | 30.93%        | 0.92x         |
| 2026-08-17 | 新應材                     | 4749       | 27.92%   | 29.81%        | 1.07x         |
| 2026-08-17 | 中砂                       | 1560       | 27.68%   | 29.63%        | 1.07x         |
| 2026-08-17 | 華邦電                     | 2344       | 48.45%   | 29.42%        | 0.61x         |
| 2026-08-17 | 牧德                       | 3563       | 31.74%   | 29.02%        | 0.91x         |
| 2026-08-17 | 羅昇                       | 8374       | 28.4%    | 28.89%        | 1.02x         |
| 2026-08-17 | 南亞                       | 1303       | 38.42%   | 28.88%        | 0.75x         |
| 2026-08-17 | 千如                       | 3236       | 30.79%   | 28.82%        | 0.94x         |
| 2026-08-17 | 統新                       | 6426       | 32.46%   | 28.69%        | 0.88x         |
| 2026-08-17 | 宏致                       | 3605       | 33.17%   | 28.68%        | 0.86x         |
| 2026-08-17 | 嘉澤                       | 3533       | 24.34%   | 28.24%        | 1.16x         |
| 2026-08-17 | 禾伸堂                     | 3026       | 29.12%   | 28.21%        | 0.97x         |
| 2026-08-17 | 信昌電                     | 6173       | 32.22%   | 28.14%        | 0.87x         |
| 2026-08-17 | 均豪                       | 5443       | 28.88%   | 27.68%        | 0.96x         |
| 2026-08-17 | 宇瞻                       | 8271       | 34.84%   | 27.61%        | 0.79x         |
| 2026-08-17 | 長園科                     | 8038       | 25.54%   | 27.58%        | 1.08x         |
| 2026-08-17 | 啟碁                       | 6285       | 22.67%   | 27.25%        | 1.2x          |
| 2026-08-17 | 立敦                       | 6175       | 30.31%   | 27.03%        | 0.89x         |
| 2026-08-17 | 新普                       | 6121       | 8.59%    | 26.94%        | 3.14x         |
| 2026-08-17 | 騰輝電子-KY                | 6672       | 30.55%   | 26.86%        | 0.88x         |
| 2026-08-17 | 嘉晶                       | 3016       | 33.65%   | 26.85%        | 0.8x          |
| 2026-08-17 | 湧德                       | 3689       | 29.36%   | 26.66%        | 0.91x         |
| 2026-08-17 | 欣銓                       | 3264       | 32.22%   | 26.61%        | 0.83x         |
| 2026-08-17 | 所羅門                     | 2359       | 21.24%   | 26.55%        | 1.25x         |
| 2026-08-17 | 華新                       | 1605       | 29.12%   | 26.24%        | 0.9x          |
| 2026-08-17 | 創見                       | 2451       | 28.88%   | 26.06%        | 0.9x          |
| 2026-08-17 | 健鼎                       | 3044       | 21.96%   | 25.91%        | 1.18x         |
| 2026-08-17 | 建準                       | 2421       | 22.43%   | 25.9%         | 1.15x         |
| 2026-08-17 | 緯穎                       | 6669       | 35.32%   | 25.62%        | 0.73x         |
| 2026-08-17 | 前鼎                       | 4908       | 26.73%   | 25.2%         | 0.94x         |
| 2026-08-17 | 亞德客-KY                  | 1590       | 17.18%   | 24.94%        | 1.45x         |
| 2026-08-17 | 耀登                       | 3138       | 22.91%   | 24.84%        | 1.08x         |
| 2026-08-17 | 迅得                       | 6438       | 22.2%    | 24.79%        | 1.12x         |
| 2026-08-17 | 日電貿                     | 3090       | 32.7%    | 24.79%        | 0.76x         |
| 2026-08-17 | 上銀                       | 2049       | 25.3%    | 24.77%        | 0.98x         |
| 2026-08-17 | 臺慶科                     | 3357       | 30.31%   | 24.54%        | 0.81x         |
| 2026-08-17 | 新日興                     | 3376       | 26.49%   | 24.37%        | 0.92x         |
| 2026-08-17 | 光寶科                     | 2301       | 24.58%   | 24.22%        | 0.99x         |
| 2026-08-17 | 國巨                       | 2327       | 31.03%   | 23.45%        | 0.76x         |
| 2026-08-17 | 嘉基                       | 6715       | 29.12%   | 23.34%        | 0.8x          |
| 2026-08-17 | 華新科                     | 2492       | 30.79%   | 23.17%        | 0.75x         |
| 2026-08-17 | M31                        | 6643       | 23.39%   | 23.01%        | 0.98x         |
| 2026-08-17 | 盟立                       | 2464       | 30.07%   | 22.98%        | 0.76x         |
| 2026-08-17 | 長興                       | 1717       | 22.91%   | 22.96%        | 1.0x          |
| 2026-08-17 | 佳必琪                     | 6197       | 23.87%   | 22.88%        | 0.96x         |
| 2026-08-17 | 勝一                       | 1773       | 12.65%   | 22.62%        | 1.79x         |
| 2026-08-17 | 兆利                       | 3548       | 15.75%   | 22.54%        | 1.43x         |
| 2026-08-17 | 統一台股增長主動式         | 00981A     | 20.58%   | 22.38%        | 1.09x         |
| 2026-08-17 | 漢唐                       | 2404       | 34.61%   | 22.35%        | 0.65x         |
| 2026-08-17 | 技嘉                       | 2376       | 17.66%   | 22.25%        | 1.26x         |
| 2026-08-17 | 乙盛-KY                    | 5243       | 21.24%   | 21.72%        | 1.02x         |
| 2026-08-17 | 帆宣                       | 6196       | 26.73%   | 21.72%        | 0.81x         |
| 2026-08-17 | 川寶                       | 1595       | 25.78%   | 21.48%        | 0.83x         |
| 2026-08-17 | 矽力-KY                    | 6415       | 26.73%   | 21.29%        | 0.8x          |
| 2026-08-17 | 力成                       | 6239       | 25.78%   | 21.23%        | 0.82x         |
| 2026-08-17 | 達明                       | 4585       | 21.94%   | 21.08%        | 0.96x         |
| 2026-08-17 | 士電                       | 1503       | 21.96%   | 20.69%        | 0.94x         |
| 2026-08-17 | 雲豹能源                   | 6869       | 12.41%   | 20.58%        | 1.66x         |
| 2026-08-17 | 台揚                       | 2314       | 23.15%   | 20.57%        | 0.89x         |
| 2026-08-17 | 仲琦                       | 2419       | 17.9%    | 20.37%        | 1.14x         |
| 2026-08-17 | 聯嘉                       | 2231       | 22.2%    | 20.35%        | 0.92x         |
| 2026-08-17 | 晟銘電                     | 3013       | 22.2%    | 20.26%        | 0.91x         |
| 2026-08-17 | 創惟                       | 6104       | 17.9%    | 19.89%        | 1.11x         |
| 2026-08-17 | 正文                       | 4906       | 17.66%   | 19.88%        | 1.13x         |
| 2026-08-17 | 神達                       | 3706       | 24.82%   | 19.84%        | 0.8x          |
| 2026-08-17 | 三福化                     | 4755       | 17.18%   | 19.83%        | 1.15x         |
| 2026-08-17 | 迎廣                       | 6117       | 19.33%   | 19.79%        | 1.02x         |
| 2026-08-17 | 京元電子                   | 2449       | 32.22%   | 19.67%        | 0.61x         |
| 2026-08-17 | 尼得科超眾                 | 6230       | 15.99%   | 19.35%        | 1.21x         |
| 2026-08-17 | 勤誠                       | 8210       | 34.13%   | 18.88%        | 0.55x         |
| 2026-08-17 | 康舒                       | 6282       | 26.73%   | 18.88%        | 0.71x         |
| 2026-08-17 | 麗臺                       | 2465       | 28.16%   | 18.73%        | 0.67x         |
| 2026-08-17 | 鴻海                       | 2317       | 17.18%   | 18.63%        | 1.08x         |
| 2026-08-17 | 華立                       | 3010       | 14.08%   | 18.22%        | 1.29x         |
| 2026-08-17 | 朋億*                      | 6613       | 24.34%   | 17.77%        | 0.73x         |
| 2026-08-17 | 祥碩                       | 5269       | 18.14%   | 17.61%        | 0.97x         |
| 2026-08-17 | 和大                       | 1536       | 18.38%   | 17.57%        | 0.96x         |
| 2026-08-17 | 樺漢                       | 6414       | 13.13%   | 17.46%        | 1.33x         |
| 2026-08-17 | 世紀                       | 5314       | 41.29%   | 17.35%        | 0.42x         |
| 2026-08-17 | 茂矽                       | 2342       | 22.91%   | 17.32%        | 0.76x         |
| 2026-08-17 | 華容                       | 5328       | 32.94%   | 17.15%        | 0.52x         |
| 2026-08-17 | 廣達                       | 2382       | 10.5%    | 16.68%        | 1.59x         |
| 2026-08-17 | 晟楠                       | 3631       | 15.27%   | 15.82%        | 1.04x         |
| 2026-08-17 | 神準                       | 3558       | 17.9%    | 15.71%        | 0.88x         |
| 2026-08-17 | 凌華                       | 6166       | 21.24%   | 15.67%        | 0.74x         |
| 2026-08-17 | 東元                       | 1504       | 17.66%   | 15.39%        | 0.87x         |
| 2026-08-17 | 易華電                     | 6552       | 17.9%    | 15.34%        | 0.86x         |
| 2026-08-17 | 聯寶                       | 6821       | 18.14%   | 15.29%        | 0.84x         |
| 2026-08-17 | 合勤控                     | 3704       | 18.62%   | 15.13%        | 0.81x         |
| 2026-08-17 | 瀚荃                       | 8103       | 21.0%    | 14.98%        | 0.71x         |
| 2026-08-17 | 聯發科                     | 2454       | 20.76%   | 14.52%        | 0.7x          |
| 2026-08-17 | 亞力                       | 1514       | 15.75%   | 13.98%        | 0.89x         |
| 2026-08-17 | 中磊                       | 5388       | 10.74%   | 13.9%         | 1.29x         |
| 2026-08-17 | 華榮                       | 1608       | 16.95%   | 13.89%        | 0.82x         |
| 2026-08-17 | 台積電                     | 2330       | 13.6%    | 13.87%        | 1.02x         |
| 2026-08-17 | 神基                       | 3005       | 13.6%    | 13.83%        | 1.02x         |
| 2026-08-17 | 華孚                       | 6235       | 15.99%   | 13.72%        | 0.86x         |
| 2026-08-17 | 信邦                       | 3023       | 11.22%   | 13.65%        | 1.22x         |
| 2026-08-17 | 超豐                       | 2441       | 17.18%   | 13.4%         | 0.78x         |
| 2026-08-17 | 華碩                       | 2357       | 17.42%   | 13.4%         | 0.77x         |
| 2026-08-17 | 廣明                       | 6188       | 14.08%   | 13.28%        | 0.94x         |
| 2026-08-17 | 威鋒電子                   | 6756       | 17.66%   | 12.62%        | 0.71x         |
| 2026-08-17 | 智原                       | 3035       | 18.38%   | 12.55%        | 0.68x         |
| 2026-08-17 | 耀勝                       | 3207       | 19.09%   | 12.52%        | 0.66x         |
| 2026-08-17 | 同致                       | 3552       | 12.41%   | 12.31%        | 0.99x         |
| 2026-08-17 | 力致                       | 3483       | 14.8%    | 12.25%        | 0.83x         |
| 2026-08-17 | 緯創                       | 3231       | 15.04%   | 12.0%         | 0.8x          |
| 2026-08-17 | 友通                       | 2397       | 12.65%   | 11.85%        | 0.94x         |

In [5]:
#均線糾結並升級為Lightbgm優化模式
import warnings
import lightgbm as lgb
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import yfinance as yf

# 忽略不必要的警告訊息
warnings.filterwarnings("ignore")

# 股票代號與名稱對應字典
stock_dict = {

   # --- 【新增：指定台股 ETF 族群】 ---
    "0050.TW": "元大台灣50",
    "0056.TW": "元大高股息",
    "00878.TW": "國泰永續高股息",
    "00770.TW": "國泰北美科技",
    "00981A.TW": "統一台股增長主動式",
    # --- 【新增：美股重點個股與 ETF】 ---
    "AAPL": "Apple 蘋果",
    "GOOG": "Google / Alphabet",
    "META": "Meta",
    "MSFT": "Microsoft 微軟",
    "NVDA": "NVIDIA 輝達",
    "TSM": "台積電 ADR",
    "TSLA": "Tesla 特斯拉",
    "ENTG": "Entegris 英特格",
    "SMR": "NuScale Power 小型核反應爐",
    "BE": "Bloom Energy 燃料電池",
    "JNJ": "Johnson & Johnson 嬌生",
    "SPCX": "SPACs ETF",
    # --- 【1. AI 伺服器與 ODM 概念股】 ---
    "2382.TW": "廣達",
    "3231.TW": "緯創",
    "6669.TW": "緯穎",
    "2317.TW": "鴻海",
    "2356.TW": "英業達",
    "2324.TW": "仁寶",
    "2376.TW": "技嘉",
    "3706.TW": "神達",
    "2377.TW": "微星",
    "2357.TW": "華碩",
    "4938.TW": "和碩",
    "3005.TW": "神基",
    "5274.TWO": "信驊",
    # --- 【2. 湧德與磁性元件 / 網通高速連接器概念股】 ---
    "3689.TWO": "湧德",
    "3357.TWO": "臺慶科",
    "6862.TW": "三集瑞-KY",
    "6821.TWO": "聯寶",
    "3207.TWO": "耀勝",
    "6197.TW": "佳必琪",
    "8103.TW": "瀚荃",
    "3526.TWO": "凡甲",
    "3605.TW": "宏致",
    # --- 【3. 網通 / 網路設備概念股】 ---
    "2345.TW": "智邦",
    "5388.TW": "中磊",
    "3558.TWO": "神準",
    "3704.TW": "合勤控",
    "4906.TW": "正文",
    # --- 【4. AI伺服器機殼 / 機構件與電子零組件概念股】 ---
    "8210.TW": "勤誠",
    "6117.TW": "迎廣",
    "6235.TW": "華孚",
    "2354.TW": "鴻準",
    "3376.TW": "新日興",
    "3548.TWO": "兆利",
    "5243.TW": "乙盛-KY",
    # --- 【5. 高速傳輸 / 介面IC / PCIe / USB4 概念股】 ---
    "4966.TWO": "譜瑞-KY",
    "5269.TW": "祥碩",
    "6104.TWO": "創惟",
    "6756.TW": "威鋒電子",
    "6715.TW": "嘉基",
    # --- 【6. AI 連接器 / 高速傳輸概念股】 ---
    "3533.TW": "嘉澤",
    "3217.TWO": "優群",
    "3023.TW": "信邦",
    "2392.TW": "正崴",
    # --- 【7. AI 核心 / 晶片設計 / ASIC 概念股】 ---
    "3035.TW": "智原",
    "6643.TWO": "M31",
    # --- 【8. AI電源供應器 / HVDC / 伺服器電源概念股】 ---
    "2308.TW": "台達電",
    "2301.TW": "光寶科",
    "6282.TW": "康舒",
    "6412.TW": "群電",
    "3665.TW": "貿聯-KY",
    # --- 【9. 液冷散熱 / 散熱模組概念股】 ---
    "3017.TW": "奇鋐",
    "3324.TWO": "雙鴻",
    "3653.TW": "健策",
    "2421.TW": "建準",
    "8996.TW": "高力",
    "3483.TWO": "力致",
    "6230.TW": "尼得科超眾",
    "3013.TW": "晟銘電",
    "6805.TW": "富世達",
    # --- 【10. BBU 備援電池模組相關概念股】 ---
    "6781.TW": "AES-KY",
    "3211.TWO": "順達",
    "6121.TWO": "新普",
    "3323.TWO": "加百裕",
    "3625.TWO": "西勝",
    "8038.TWO": "長園科",
    "4931.TWO": "新盛力",
    # --- 【11. 電力概念股 (重電、變壓器、電線電纜、儲能)】 ---
    "1519.TW": "華城",
    "1513.TW": "中興電",
    "1514.TW": "亞力",
    "1503.TW": "士電",
    "1609.TW": "大亞",
    "1605.TW": "華新",
    "1608.TW": "華榮",
    "6869.TW": "雲豹能源",
    # --- 【12. PCB / ABF載板 / CCL 相關概念股】 ---
    "3037.TW": "欣興",
    "8046.TW": "南電",
    "3189.TW": "景碩",
    "4958.TW": "臻鼎-KY",
    "2368.TW": "金像電",
    "3044.TW": "健鼎",
    "2313.TW": "華通",
    "8155.TWO": "博智",
    "2383.TW": "台光電",
    "6274.TWO": "台燿",
    "6213.TW": "聯茂",
    # --- 【13. 記憶體相關概念股】 ---
    "2344.TW": "華邦電",
    "2408.TW": "南亞科",
    "2337.TW": "旺宏",
    "3006.TW": "晶豪科",
    "3260.TWO": "威剛",
    "2451.TW": "創見",
    "4967.TW": "十銓",
    "8271.TW": "宇瞻",
    "5289.TWO": "宜鼎",
    "8299.TWO": "群聯",
    "5351.TWO": "鈺創",
    # --- 【14. 光通訊 / 矽光子 / CPO 概念股】 ---
    "4979.TWO": "華星光",
    "6442.TW": "光聖",
    "4908.TWO": "前鼎",
    "3163.TWO": "波若威",
    "3450.TW": "聯鈞",
    "6426.TW": "統新",
    "4977.TW": "眾達-KY",
    "6530.TWO": "創威",
    "3363.TWO": "上詮",
    "3234.TWO": "光環",
    "4903.TWO": "聯光通",
    "3081.TWO": "聯亞",
    "4991.TWO": "環宇-KY",
    "4971.TWO": "IET-KY",
    "6588.TWO": "東典光電",
    # --- 【15. 低軌衛星 / 太空通訊概念股】 ---
    "3491.TWO": "昇達科",
    "2314.TW": "台揚",
    "6285.TW": "啟碁",
    "3105.TWO": "穩懋",
    "2455.TW": "全新",
    "3138.TW": "耀登",
    "2419.TW": "仲琦",
    # --- 【16. 被動元件族群】 ---
    "2327.TW": "國巨",
    "2492.TW": "華新科",
    "2375.TW": "凱美",
    "2478.TW": "大毅",
    "3026.TW": "禾伸堂",
    "3090.TW": "日電貿",
    "6173.TWO": "信昌電",
    "6155.TW": "鈞寶",
    "6175.TWO": "立敦",
    "5328.TWO": "華容",
    "3236.TWO": "千如",
    # --- 【17. 機器人相關概念股】 ---
    "2049.TW": "上銀",
    "4576.TW": "大銀微系統",
    "4585.TW": "達明",
    "2359.TW": "所羅門",
    "6188.TWO": "廣明",
    "8374.TW": "羅昇",
    "5443.TWO": "均豪",
    "6640.TWO": "均華",
    "2464.TW": "盟立",
    "6215.TW": "和椿",
    "4562.TW": "穎漢",
    "1590.TW": "亞德客-KY",
    "1504.TW": "東元",
    # --- 【18. 半導體封裝與設備概念股】 ---
    "3711.TW": "日月光投控",
    "2449.TW": "京元電子",
    "6257.TW": "矽格",
    "3264.TWO": "欣銓",
    "6239.TW": "力成",
    "2329.TW": "華泰",
    "2441.TW": "超豐",
    "3131.TWO": "弘塑",
    "3583.TW": "辛耘",
    "6187.TWO": "萬潤",
    "2467.TW": "志聖",
    "8027.TWO": "鈦昇",
    "3481.TW": "群創",
    "2409.TW": "友達",
    # --- 【19. 半導體應用材料 / 耗材概念股】 ---
    "5434.TW": "崇越",
    "3010.TW": "華立",
    "1560.TW": "中砂",
    "3680.TWO": "家登",
    "5234.TW": "達興材料",
    "4749.TWO": "新應材",
    "8028.TW": "昇陽半導體",
    "6515.TW": "穎崴",
    "6683.TWO": "雍智科技",
    "6510.TWO": "精測",
    "6223.TWO": "旺矽",
    # --- 【20. 核心半導體 / IC設計 / 晶圓代工】 ---
    "2330.TW": "台積電",
    "2303.TW": "聯電",
    "2454.TW": "聯發科",
    "3034.TW": "聯詠",
    "3661.TW": "世芯-KY",
    "3443.TW": "創意",
    "4961.TW": "天鈺",
    "6415.TW": "矽力-KY",
    "6531.TW": "愛普*",
    # --- 【21. 家登概念股 / 半導體載具與設備夥伴】 ---
    "2404.TW": "漢唐",
    "1773.TW": "勝一",
    # --- 【22. 光學鏡頭與先進設備】 ---
    "3008.TW": "大立光",
    "4915.TW": "先進光",
    "5288.TW": "匯鑽科",
    "3644.TWO": "凌嘉科",
    "7769.TW": "鴻勁",
    "1303.TW": "南亞",
    # --- 【23. 工業電腦 (IPC) 相關概念股】 ---
    "2395.TW": "研華",
    "6166.TW": "凌華",
    "8050.TWO": "廣積",
    "3556.TWO": "禾瑞亞",
    "2414.TW": "精技",
    "6414.TW": "樺漢",
    "3022.TW": "威強電",
    "2397.TW": "友通",
    "5314.TWO": "世紀",
    "2393.TW": "億光",
    "2465.TW": "麗臺",
    "5536.TWO": "聖暉*",
    # --- 【24. 電動車 (EV) 與車用電子相關概念股】 ---
    "2201.TW": "裕隆",
    "2204.TW": "中華",
    "2206.TW": "三陽工業",
    "1536.TW": "和大",
    "2231.TW": "聯嘉",
    "3552.TWO": "同致",
    "6279.TWO": "胡連",
    # --- 【25. 其他與基礎建設】 ---
    "2353.TW": "宏碁",
    "8163.TW": "達方",
    "8043.TWO": "蜜望實",
    "2892.TW": "第一金",
    "5880.TW": "合庫金",
    "1210.TW": "大成",
    "1215.TW": "卜蜂",
    "1216.TW": "統一",
    "2912.TW": "統一超",
    "5903.TWO": "全家",
    "6770.TW": "力積電",
    "2342.TW": "茂矽",
    "3707.TWO": "漢磊",
    "3016.TW": "嘉晶",
    "6196.TW": "帆宣",
    "6139.TW": "亞翔",
    "6613.TWO": "朋億*",
    "4755.TW": "三福化",
    "4768.TWO": "晶呈科技",
    "3563.TW": "牧德",
    "1717.TW": "長興",
    "1815.TWO": "富喬",
    "1802.TW": "台玻",
    "5340.TWO": "建榮",
    "5475.TWO": "德宏",
    "3167.TW": "大量",
    "6438.TW": "迅得",
    "1595.TWO": "川寶",
    "6147.TWO": "頎邦",
    "8150.TW": "南茂",
    "6552.TW": "易華電",
    "3305.TW": "昇貿",
    "3631.TWO": "晟楠",
    "2059.TW": "川湖",
    "6584.TWO": "南俊國際",
    "8358.TWO": "金居",
    "8021.TW": "尖點",
    "6672.TW": "騰輝電子-KY",

}


def compute_features(df, market_df):
  """執行 4 大類特徵工程與防洩漏處理 (LightGBM 優化版)"""
  d = df.copy()

  # --- A. 價格型態與波動度特徵 ---
  d["Close_Slope"] = (
      d["Close"].rolling(5).apply(lambda x: np.polyfit(range(5), x, 1)[0], raw=True)
  )

  body = np.abs(d["Close"] - d["Open"])
  body_safe = np.where(body == 0, 1e-6, body)
  d["Upper_Shadow_Ratio"] = (
      d["High"] - np.maximum(d["Close"], d["Open"])
  ) / body_safe
  d["Lower_Shadow_Ratio"] = (
      np.minimum(d["Close"], d["Open"]) - d["Low"]
  ) / body_safe

  d["Gap"] = (d["Open"] - d["Close"].shift(1)) / d["Close"].shift(1)

  high_low = d["High"] - d["Low"]
  high_close = np.abs(d["High"] - d["Close"].shift(1))
  low_close = np.abs(d["Low"] - d["Close"].shift(1))
  tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
  atr14 = tr.rolling(14).mean()
  d["NATR"] = atr14 / d["Close"]

  ma20 = d["Close"].rolling(20).mean()
  std20 = d["Close"].rolling(20).std()
  upper_band = ma20 + (2 * std20)
  lower_band = ma20 - (2 * std20)
  d["BB_Bandwidth"] = (upper_band - lower_band) / ma20

  ma5 = d["Close"].rolling(5).mean()
  d["BIAS_5"] = (d["Close"] - ma5) / ma5

  # --- B. 量能與資金成本特徵 ---
  vol_mean5 = d["Volume"].rolling(5).mean()
  d["Volume_Explosion"] = d["Volume"] / (vol_mean5 + 1e-6)

  typical_price = (d["High"] + d["Low"] + d["Close"]) / 3
  vwap = (typical_price * d["Volume"]).rolling(5).sum() / (
      d["Volume"].rolling(5).sum() + 1e-6
  )
  d["VWAP_BIAS"] = (d["Close"] - vwap) / vwap

  obv = (np.sign(d["Close"].diff()) * d["Volume"]).fillna(0).cumsum()
  d["OBV_Slope"] = (
      obv.rolling(5).apply(lambda x: np.polyfit(range(5), x, 1)[0], raw=True)
  )
  d["Turnover_Rate"] = d["Volume"] / (d["Volume"].rolling(60).mean() + 1e-6)

  # --- C. 深層籌碼與信用交易特徵 ---
  d["Foreign_Buy_Ratio"] = 0.0
  d["Trust_Buy_Ratio"] = 0.0
  d["Inst_Sync"] = 0
  d["Margin_Change_5d"] = 0.0
  d["Short_Margin_Ratio"] = 0.0

  # --- D. 市場相對強度特徵 ---
  stock_ret5 = d["Close"].pct_change(5)
  market_ret5 = market_df["Close"].pct_change(5)
  d["Alpha_5d"] = stock_ret5 - market_ret5

  feature_cols = [
      "Close_Slope",
      "Upper_Shadow_Ratio",
      "Lower_Shadow_Ratio",
      "Gap",
      "NATR",
      "BB_Bandwidth",
      "BIAS_5",
      "Volume_Explosion",
      "VWAP_BIAS",
      "OBV_Slope",
      "Turnover_Rate",
      "Foreign_Buy_Ratio",
      "Trust_Buy_Ratio",
      "Inst_Sync",
      "Margin_Change_5d",
      "Short_Margin_Ratio",
      "Alpha_5d",
  ]

  # 特徵位移防洩漏
  for col in feature_cols:
    d[col] = d[col].shift(1)

  return d, feature_cols


print("步驟零：正在下載大盤基準資料 (^TWII)...")
market_df = yf.download("^TWII", period="3y", progress=False)
if isinstance(market_df.columns, pd.MultiIndex):
  market_df.columns = market_df.columns.get_level_values(0)

print(
    "步驟一：開始進行個股批次下載與運算，並套用流動性與均線糾結篩選條件..."
)
predictions = []

all_tickers = list(stock_dict.keys())
batch_data = yf.download(all_tickers, period="2y", progress=False, group_by="ticker")

for ticker, name in stock_dict.items():
  try:
    if len(all_tickers) > 1:
      df = batch_data[ticker].dropna(how="all")
    else:
      df = batch_data.dropna(how="all")

    if df.empty or len(df) < 250:
      continue
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)

    # 計算篩選條件所需的指標（直接使用當天實際數據，不作 shift）
    vol_mean_5 = df["Volume"].rolling(5).mean()
    ma5 = df["Close"].rolling(5).mean()
    ma10 = df["Close"].rolling(10).mean()
    ma20 = df["Close"].rolling(20).mean()
    ma_max = pd.concat([ma5, ma10, ma20], axis=1).max(axis=1)
    ma_min = pd.concat([ma5, ma10, ma20], axis=1).min(axis=1)

    # 條件 1：5日均量 >= 500 張 (500,000 股)
    liquidity_ok = vol_mean_5 >= 500000
    # 條件 2：5日線、10日線、20日線差距在 3% 以內
    ma_tangle = (ma_max - ma_min) / (ma_min + 1e-6) <= 0.03

    # 標籤定義：未來 10 個交易日內最高價曾漲幅達 10%
    horizon = 10
    threshold = 0.10
    future_max = (
        df["Close"]
        .shift(-1)
        .iloc[::-1]
        .rolling(window=horizon, min_periods=1)
        .max()
        .iloc[::-1]
    )
    future_return = (future_max - df["Close"]) / df["Close"]
    df["Target"] = (future_return >= threshold).astype(int)

    # 執行特徵工程與防洩漏處理
    df_feat, feature_cols = compute_features(df, market_df)

    df_clean = df_feat.dropna(subset=feature_cols + ["Target"])
    if len(df_clean) < 60:
      continue

    # 迴圈計算最後 5 個交易日的逐日預測
    for i in range(-5, 0):
      # 取得當前預測日期的 Index 標籤
      target_idx = df_clean.index[i]

      # 套用篩選條件：若當天不符合流動性或均線糾結，則略過
      if not liquidity_ok.loc[target_idx] or not ma_tangle.loc[target_idx]:
        continue

      X_train = df_clean[feature_cols].iloc[:i]
      y_train = df_clean["Target"].iloc[:i]

      if len(y_train) < 50 or len(y_train.unique()) < 2:
        continue

      # 極端值處理 (Winsorization 1% 至 99%)
      lower_bound = X_train.quantile(0.01)
      upper_bound = X_train.quantile(0.99)
      X_train_clipped = X_train.clip(lower_bound, upper_bound, axis=1)

      train_base = y_train.mean()

      # 切分出驗證集供 LightGBM 早停機制使用
      if len(X_train_clipped) > 30:
        X_tr, X_val, y_tr, y_val = train_test_split(
            X_train_clipped, y_train, test_size=0.2, shuffle=False
        )
      else:
        X_tr, X_val, y_tr, y_val = (
            X_train_clipped,
            X_train_clipped,
            y_train,
            y_train,
        )

      # 建立 LightGBM 模型並加入早停機制
      model = lgb.LGBMClassifier(
          n_estimators=300,
          learning_rate=0.03,
          max_depth=4,
          random_state=42,
          verbose=-1,
      )

      model.fit(
          X_tr,
          y_tr,
          eval_set=[(X_val, y_val)],
          callbacks=[lgb.early_stopping(stopping_rounds=30, verbose=False)],
      )

      # 取得目標當天的特徵
      target_features = df_clean[feature_cols].iloc[[i]].copy()
      target_features = target_features.clip(lower_bound, upper_bound, axis=1)

      if target_features.dropna().empty:
        continue

      prob = model.predict_proba(target_features)[0][1]
      lift_val = float(prob) / float(train_base) if train_base > 0 else 0.0
      pred_date = target_idx.strftime("%Y-%m-%d")

      predictions.append({
          "預測日期": pred_date,
          "股票名稱": name,
          "股票代號": ticker.split(".")[0],
          "Base y": f"{round(float(train_base) * 100, 2)}%",
          "raw_prob": float(prob),
          "y成立機率值": f"{round(float(prob) * 100, 2)}%",
          "10% Lift 值": f"{round(lift_val, 2)}x",
      })
  except Exception:
    pass

final_output_df = pd.DataFrame(predictions)
if not final_output_df.empty:
  final_output_df = final_output_df.sort_values(
      by=["預測日期", "raw_prob"], ascending=[False, False]
  )

  print("\n" + "=" * 75)
  print(
      " 最近 5 個交易日符合篩選條件之個股逐日預測結果清單 (流動性 & 均線糾結過濾版)"
  )
  print("=" * 75)
  print(
      final_output_df[[
          "預測日期",
          "股票名稱",
          "股票代號",
          "Base y",
          "y成立機率值",
          "10% Lift 值",
      ]].to_markdown(index=False)
  )
else:
  print("目前最近 5 個交易日內，沒有符合「5日均量 >= 500張 且 均線糾結 3%」的股票。")

步驟零：正在下載大盤基準資料 (^TWII)...
步驟一：開始進行個股批次下載與運算，並套用流動性與均線糾結篩選條件...

===========================================================================
 最近 5 個交易日符合篩選條件之個股逐日預測結果清單 (流動性 & 均線糾結過濾版)
===========================================================================
| 預測日期   | 股票名稱          | 股票代號   | Base y   | y成立機率值   | 10% Lift 值   |
|:-----------|:------------------|:-----------|:---------|:--------------|:--------------|
| 2026-08-17 | 貿聯-KY           | 3665       | 42.0%    | 40.66%        | 0.97x         |
| 2026-08-17 | 亞翔              | 6139       | 36.75%   | 38.24%        | 1.04x         |
| 2026-08-17 | 大毅              | 2478       | 28.16%   | 38.21%        | 1.36x         |
| 2026-08-17 | 智邦              | 2345       | 36.28%   | 37.06%        | 1.02x         |
| 2026-08-17 | 矽格              | 6257       | 25.78%   | 35.97%        | 1.4x          |
| 2026-08-17 | 鈦昇              | 8027       | 29.59%   | 35.75%        | 1.21x         |
| 2026-08-17 | 威剛              | 3260       | 33.41%   | 34.42%        | 1.03x         |
| 2026-08-17 | 弘塑              | 3131       | 36.04%   | 33.88%        | 0.94x         |
| 2026-08-17 | 辛耘              | 3583       | 25.54%   | 32.83%        | 1.29x         |
| 2026-08-17 | 華泰              | 2329       | 28.88%   | 32.13%        | 1.11x         |
| 2026-08-17 | 昇陽半導體        | 8028       | 33.41%   | 31.66%        | 0.95x         |
| 2026-08-17 | 啟碁              | 6285       | 22.67%   | 27.25%        | 1.2x          |
| 2026-08-17 | 立敦              | 6175       | 30.31%   | 27.03%        | 0.89x         |
| 2026-08-17 | 佳必琪            | 6197       | 23.87%   | 22.88%        | 0.96x         |
| 2026-08-17 | 漢唐              | 2404       | 34.61%   | 22.35%        | 0.65x         |
| 2026-08-17 | 帆宣              | 6196       | 26.73%   | 21.72%        | 0.81x         |
| 2026-08-17 | 士電              | 1503       | 21.96%   | 20.69%        | 0.94x         |
| 2026-08-17 | 晟銘電            | 3013       | 22.2%    | 20.36%        | 0.92x         |
| 2026-08-17 | 神達              | 3706       | 24.82%   | 19.84%        | 0.8x          |
| 2026-08-17 | 京元電子          | 2449       | 32.22%   | 19.67%        | 0.61x         |
| 2026-08-17 | 祥碩              | 5269       | 18.14%   | 17.61%        | 0.97x         |
| 2026-08-17 | 和大              | 1536       | 18.38%   | 17.57%        | 0.96x         |
| 2026-08-17 | 凌華              | 6166       | 21.24%   | 15.67%        | 0.74x         |
| 2026-08-17 | 亞力              | 1514       | 15.75%   | 13.98%        | 0.89x         |
| 2026-08-17 | 台積電            | 2330       | 13.6%    | 13.87%        | 1.02x         |
| 2026-08-17 | 神基              | 3005       | 13.6%    | 13.83%        | 1.02x         |
| 2026-08-17 | 智原              | 3035       | 18.38%   | 12.55%        | 0.68x         |
| 2026-08-17 | 譜瑞-KY           | 4966       | 15.99%   | 11.88%        | 0.74x         |
| 2026-08-17 | 卜蜂              | 1215       | 8.59%    | 10.72%        | 1.25x         |
| 2026-08-17 | 裕隆              | 2201       | 7.4%     | 10.31%        | 1.39x         |
| 2026-08-17 | 優群              | 3217       | 15.75%   | 9.72%         | 0.62x         |
| 2026-08-17 | 崇越              | 5434       | 14.8%    | 8.26%         | 0.56x         |
| 2026-08-17 | 群電              | 6412       | 13.6%    | 6.35%         | 0.47x         |
| 2026-08-17 | 聯電              | 2303       | 18.62%   | 6.27%         | 0.34x         |
| 2026-08-17 | 國泰永續高股息    | 00878      | 5.24%    | 1.85%         | 0.35x         |
| 2026-08-17 | 聯詠              | 3034       | 6.92%    | 1.6%          | 0.23x         |
| 2026-08-17 | 達方              | 8163       | 8.83%    | 1.27%         | 0.14x         |
| 2026-08-17 | 中華              | 2204       | 2.15%    | 0.0%          | 0.0x          |
| 2026-08-17 | 大成              | 1210       | 0.72%    | 0.0%          | 0.0x          |
| 2026-08-14 | 矽格              | 6257       | 25.84%   | 45.37%        | 1.76x         |
| 2026-08-14 | 臻鼎-KY           | 4958       | 32.06%   | 41.46%        | 1.29x         |
| 2026-08-14 | 辛耘              | 3583       | 25.6%    | 33.91%        | 1.32x         |
| 2026-08-14 | 華泰              | 2329       | 28.95%   | 32.91%        | 1.14x         |
| 2026-08-14 | 鈦昇              | 8027       | 29.67%   | 31.78%        | 1.07x         |
| 2026-08-14 | 佳必琪            | 6197       | 23.92%   | 30.37%        | 1.27x         |
| 2026-08-14 | 京元電子          | 2449       | 32.3%    | 29.56%        | 0.92x         |
| 2026-08-14 | 新應材            | 4749       | 27.99%   | 29.06%        | 1.04x         |
| 2026-08-14 | 漢唐              | 2404       | 34.69%   | 28.12%        | 0.81x         |
| 2026-08-14 | 立敦              | 6175       | 30.38%   | 28.05%        | 0.92x         |
| 2026-08-14 | 嘉澤              | 3533       | 24.4%    | 28.03%        | 1.15x         |
| 2026-08-14 | 樺漢              | 6414       | 13.16%   | 24.13%        | 1.83x         |
| 2026-08-14 | Tesla 特斯拉      | TSLA       | 24.82%   | 22.89%        | 0.92x         |
| 2026-08-14 | 帆宣              | 6196       | 26.79%   | 21.5%         | 0.8x          |
| 2026-08-14 | 大毅              | 2478       | 28.23%   | 20.41%        | 0.72x         |
| 2026-08-14 | 士電              | 1503       | 22.01%   | 19.85%        | 0.9x          |
| 2026-08-14 | 祥碩              | 5269       | 18.18%   | 18.97%        | 1.04x         |
| 2026-08-14 | 和大              | 1536       | 18.42%   | 17.62%        | 0.96x         |
| 2026-08-14 | 神達              | 3706       | 24.88%   | 17.27%        | 0.69x         |
| 2026-08-14 | 凌華              | 6166       | 21.29%   | 16.59%        | 0.78x         |
| 2026-08-14 | Meta              | META       | 16.3%    | 16.57%        | 1.02x         |
| 2026-08-14 | 神基              | 3005       | 13.64%   | 15.28%        | 1.12x         |
| 2026-08-14 | 合勤控            | 3704       | 18.66%   | 14.89%        | 0.8x          |
| 2026-08-14 | Google / Alphabet | GOOG       | 14.84%   | 14.74%        | 0.99x         |
| 2026-08-14 | 亞力              | 1514       | 15.79%   | 14.44%        | 0.91x         |
| 2026-08-14 | 台積電            | 2330       | 13.64%   | 13.93%        | 1.02x         |
| 2026-08-14 | 廣明              | 6188       | 14.11%   | 12.98%        | 0.92x         |
| 2026-08-14 | 智原              | 3035       | 18.42%   | 12.63%        | 0.69x         |
| 2026-08-14 | 譜瑞-KY           | 4966       | 16.03%   | 11.82%        | 0.74x         |
| 2026-08-14 | 裕隆              | 2201       | 7.42%    | 11.69%        | 1.58x         |
| 2026-08-14 | 群電              | 6412       | 13.64%   | 11.0%         | 0.81x         |
| 2026-08-14 | 中磊              | 5388       | 10.77%   | 10.97%        | 1.02x         |
| 2026-08-14 | 卜蜂              | 1215       | 8.61%    | 10.75%        | 1.25x         |
| 2026-08-14 | 優群              | 3217       | 15.79%   | 9.82%         | 0.62x         |
| 2026-08-14 | 崇越              | 5434       | 14.83%   | 9.81%         | 0.66x         |
| 2026-08-14 | 聯電              | 2303       | 18.66%   | 6.88%         | 0.37x         |
| 2026-08-14 | 達方              | 8163       | 8.85%    | 1.35%         | 0.15x         |
| 2026-08-14 | 中華              | 2204       | 2.15%    | 0.01%         | 0.01x         |
| 2026-08-14 | 大成              | 1210       | 0.72%    | 0.01%         | 0.02x         |
| 2026-08-13 | 鈞寶              | 6155       | 30.46%   | 43.75%        | 1.44x         |
| 2026-08-13 | 臻鼎-KY           | 4958       | 32.13%   | 41.5%         | 1.29x         |
| 2026-08-13 | 凱美              | 2375       | 31.41%   | 37.94%        | 1.21x         |
| 2026-08-13 | 辛耘              | 3583       | 25.66%   | 33.9%         | 1.32x         |
| 2026-08-13 | 華泰              | 2329       | 29.02%   | 32.71%        | 1.13x         |
| 2026-08-13 | 矽格              | 6257       | 25.9%    | 27.36%        | 1.06x         |
| 2026-08-13 | 嘉澤              | 3533       | 24.46%   | 26.74%        | 1.09x         |
| 2026-08-13 | 啟碁              | 6285       | 22.78%   | 25.53%        | 1.12x         |
| 2026-08-13 | 華容              | 5328       | 33.09%   | 23.73%        | 0.72x         |
| 2026-08-13 | 佳必琪            | 6197       | 23.98%   | 23.27%        | 0.97x         |
| 2026-08-13 | Tesla 特斯拉      | TSLA       | 24.88%   | 22.89%        | 0.92x         |
| 2026-08-13 | 漢唐              | 2404       | 34.77%   | 22.66%        | 0.65x         |
| 2026-08-13 | 晟銘電            | 3013       | 22.3%    | 22.64%        | 1.02x         |
| 2026-08-13 | 廣達              | 2382       | 10.55%   | 21.57%        | 2.04x         |
| 2026-08-13 | 帆宣              | 6196       | 26.86%   | 21.27%        | 0.79x         |
| 2026-08-13 | 京元電子          | 2449       | 32.37%   | 20.42%        | 0.63x         |
| 2026-08-13 | 茂矽              | 2342       | 23.02%   | 18.14%        | 0.79x         |
| 2026-08-13 | 樺漢              | 6414       | 13.19%   | 18.09%        | 1.37x         |
| 2026-08-13 | 士電              | 1503       | 22.06%   | 17.58%        | 0.8x          |
| 2026-08-13 | Meta              | META       | 16.34%   | 16.57%        | 1.01x         |
| 2026-08-13 | 東元              | 1504       | 17.75%   | 15.48%        | 0.87x         |
| 2026-08-13 | 神達              | 3706       | 24.94%   | 15.41%        | 0.62x         |
| 2026-08-13 | 祥碩              | 5269       | 18.23%   | 15.05%        | 0.83x         |
| 2026-08-13 | 合勤控            | 3704       | 18.71%   | 14.57%        | 0.78x         |
| 2026-08-13 | 神基              | 3005       | 13.67%   | 14.18%        | 1.04x         |
| 2026-08-13 | 亞力              | 1514       | 15.83%   | 14.16%        | 0.89x         |
| 2026-08-13 | 中磊              | 5388       | 10.79%   | 13.94%        | 1.29x         |
| 2026-08-13 | 台積電            | 2330       | 13.67%   | 13.92%        | 1.02x         |
| 2026-08-13 | 家登              | 3680       | 19.66%   | 12.71%        | 0.65x         |
| 2026-08-13 | 譜瑞-KY           | 4966       | 16.07%   | 11.56%        | 0.72x         |
| 2026-08-13 | 卜蜂              | 1215       | 8.63%    | 10.78%        | 1.25x         |
| 2026-08-13 | 優群              | 3217       | 15.83%   | 10.74%        | 0.68x         |
| 2026-08-13 | 崇越              | 5434       | 14.87%   | 9.05%         | 0.61x         |
| 2026-08-13 | 中興電            | 1513       | 11.27%   | 7.87%         | 0.7x          |
| 2026-08-13 | 群電              | 6412       | 13.67%   | 6.46%         | 0.47x         |
| 2026-08-13 | 裕隆              | 2201       | 7.43%    | 4.7%          | 0.63x         |
| 2026-08-13 | 聯電              | 2303       | 18.71%   | 4.1%          | 0.22x         |
| 2026-08-13 | 廣明              | 6188       | 14.15%   | 3.72%         | 0.26x         |
| 2026-08-13 | 國泰永續高股息    | 00878      | 5.26%    | 1.53%         | 0.29x         |
| 2026-08-13 | 達方              | 8163       | 8.87%    | 1.4%          | 0.16x         |
| 2026-08-13 | 中華              | 2204       | 2.16%    | 0.04%         | 0.02x         |
| 2026-08-13 | 大成              | 1210       | 0.72%    | 0.0%          | 0.0x          |
| 2026-08-12 | 蜜望實            | 8043       | 41.35%   | 55.26%        | 1.34x         |
| 2026-08-12 | 華容              | 5328       | 33.17%   | 40.09%        | 1.21x         |
| 2026-08-12 | 智邦              | 2345       | 36.54%   | 36.44%        | 1.0x          |
| 2026-08-12 | 嘉澤              | 3533       | 24.52%   | 27.5%         | 1.12x         |
| 2026-08-12 | 啟碁              | 6285       | 22.84%   | 25.42%        | 1.11x         |
| 2026-08-12 | 佳必琪            | 6197       | 24.04%   | 24.86%        | 1.03x         |
| 2026-08-12 | 漢唐              | 2404       | 34.86%   | 23.91%        | 0.69x         |
| 2026-08-12 | 勤誠              | 8210       | 34.38%   | 20.82%        | 0.61x         |
| 2026-08-12 | Google / Alphabet | GOOG       | 14.91%   | 20.82%        | 1.4x          |
| 2026-08-12 | 士電              | 1503       | 22.12%   | 20.6%         | 0.93x         |
| 2026-08-12 | 台積電 ADR        | TSM        | 18.09%   | 18.4%         | 1.02x         |
| 2026-08-12 | 群電              | 6412       | 13.7%    | 18.21%        | 1.33x         |
| 2026-08-12 | 東元              | 1504       | 17.79%   | 15.53%        | 0.87x         |
| 2026-08-12 | 合勤控            | 3704       | 18.75%   | 15.23%        | 0.81x         |
| 2026-08-12 | 祥碩              | 5269       | 18.27%   | 14.5%         | 0.79x         |
| 2026-08-12 | 神基              | 3005       | 13.7%    | 14.22%        | 1.04x         |
| 2026-08-12 | 亞力              | 1514       | 15.87%   | 14.2%         | 0.9x          |
| 2026-08-12 | 台積電            | 2330       | 13.7%    | 13.99%        | 1.02x         |
| 2026-08-12 | 廣明              | 6188       | 14.18%   | 13.35%        | 0.94x         |
| 2026-08-12 | 優群              | 3217       | 15.87%   | 11.81%        | 0.74x         |
| 2026-08-12 | 卜蜂              | 1215       | 8.65%    | 11.69%        | 1.35x         |
| 2026-08-12 | 譜瑞-KY           | 4966       | 16.11%   | 11.5%         | 0.71x         |
| 2026-08-12 | 仁寶              | 2324       | 14.9%    | 8.42%         | 0.56x         |
| 2026-08-12 | 中興電            | 1513       | 11.3%    | 7.89%         | 0.7x          |
| 2026-08-12 | 神達              | 3706       | 25.0%    | 7.19%         | 0.29x         |
| 2026-08-12 | 元大台灣50        | 0050       | 9.11%    | 6.41%         | 0.7x          |
| 2026-08-12 | 中華              | 2204       | 2.16%    | 4.73%         | 2.19x         |
| 2026-08-12 | 國泰永續高股息    | 00878      | 5.28%    | 1.54%         | 0.29x         |
| 2026-08-12 | 達方              | 8163       | 8.89%    | 1.4%          | 0.16x         |
| 2026-08-12 | 裕隆              | 2201       | 7.45%    | 1.33%         | 0.18x         |
| 2026-08-12 | 大成              | 1210       | 0.72%    | 0.0%          | 0.0x          |
| 2026-08-11 | 華容              | 5328       | 33.25%   | 42.51%        | 1.28x         |
| 2026-08-11 | 神達              | 3706       | 25.06%   | 34.04%        | 1.36x         |
| 2026-08-11 | 士電              | 1503       | 22.17%   | 20.9%         | 0.94x         |
| 2026-08-11 | 台積電 ADR        | TSM        | 18.14%   | 17.6%         | 0.97x         |
| 2026-08-11 | 東元              | 1504       | 17.83%   | 15.53%        | 0.87x         |
| 2026-08-11 | 群電              | 6412       | 13.73%   | 14.56%        | 1.06x         |
| 2026-08-11 | 祥碩              | 5269       | 18.31%   | 14.55%        | 0.79x         |
| 2026-08-11 | Google / Alphabet | GOOG       | 14.95%   | 14.53%        | 0.97x         |
| 2026-08-11 | 神基              | 3005       | 13.73%   | 14.22%        | 1.04x         |
| 2026-08-11 | 台積電            | 2330       | 13.73%   | 13.99%        | 1.02x         |
| 2026-08-11 | 亞力              | 1514       | 15.9%    | 13.81%        | 0.87x         |
| 2026-08-11 | 優群              | 3217       | 15.9%    | 11.81%        | 0.74x         |
| 2026-08-11 | 卜蜂              | 1215       | 8.67%    | 11.69%        | 1.35x         |
| 2026-08-11 | 中興電            | 1513       | 11.33%   | 7.89%         | 0.7x          |
| 2026-08-11 | 仁寶              | 2324       | 14.7%    | 7.54%         | 0.51x         |
| 2026-08-11 | 凡甲              | 3526       | 10.12%   | 7.26%         | 0.72x         |
| 2026-08-11 | 元大台灣50        | 0050       | 9.13%    | 6.55%         | 0.72x         |
| 2026-08-11 | 精技              | 2414       | 6.02%    | 3.22%         | 0.53x         |
| 2026-08-11 | 裕隆              | 2201       | 7.47%    | 2.9%          | 0.39x         |
| 2026-08-11 | 國泰永續高股息    | 00878      | 5.29%    | 0.81%         | 0.15x         |
| 2026-08-11 | 中華              | 2204       | 2.17%    | 0.01%         | 0.0x          |
| 2026-08-11 | 大成              | 1210       | 0.72%    | 0.0%          | 0.0x          |
| 2026-08-10 | 台積電 ADR        | TSM        | 18.18%   | 16.94%        | 0.93x         |